apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-service
  description: This is a sample service registered in Backstage
  annotations:
    github.com/project-slug: dy-org/dy-service
spec:
  type: service
  lifecycle: production
  owner: github-team-name
